In [1]:
import numpy as np
import cv2

In [13]:
img = cv2.imread('C:/Users/Server_PC/Documents/python/images/flemingo.jpg')

In [14]:
print(img)

[[[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 [[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 [[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 ...

 [[167 134  88]
  [167 134  88]
  [167 134  88]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]

 [[171 141  94]
  [171 141  94]
  [172 142  95]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]

 [[177 147 100]
  [177 147 100]
  [178 148 101]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]]


In [15]:
img.shape

(640, 640, 3)

In [20]:
cv2.imshow('example',img)
cv2.waitKey(0) #milliseconds
cv2.destroyAllWindows()

In [24]:
# save an iamge
cv2.imwrite('./images/example.png',img)

True