In [2]:
import numpy as np
import cv2

In [3]:
img = cv2.imread('./example.png')

In [5]:
def display(winame, img):
    cv2.imshow(winame, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [17]:
display("bird", img)

'bird'

array([[[188, 163, 119],
        [189, 164, 120],
        [189, 164, 120],
        ...,
        [188, 163, 119],
        [188, 163, 119],
        [188, 163, 119]],

       [[188, 163, 119],
        [189, 164, 120],
        [189, 164, 120],
        ...,
        [188, 163, 119],
        [188, 163, 119],
        [188, 163, 119]],

       [[188, 163, 119],
        [189, 164, 120],
        [189, 164, 120],
        ...,
        [188, 163, 119],
        [188, 163, 119],
        [188, 163, 119]],

       ...,

       [[167, 134,  88],
        [167, 134,  88],
        [167, 134,  88],
        ...,
        [177, 144,  98],
        [177, 144,  98],
        [177, 144,  98]],

       [[171, 141,  94],
        [171, 141,  94],
        [172, 142,  95],
        ...,
        [177, 144,  98],
        [177, 144,  98],
        [177, 144,  98]],

       [[177, 147, 100],
        [177, 147, 100],
        [178, 148, 101],
        ...,
        [177, 144,  98],
        [177, 144,  98],
        [177, 144,  98]]

Transforming

In [10]:
tx = 100
ty = 150

array([[  1.,   0., 100.],
       [  0.,   1., 150.]], dtype=float32)

In [12]:
display("shifted right 100, down 150", shifted_img)

In [14]:
def translation(image, tx,ty):
    M = np.float32([[1,0,tx],
                [0,1,ty]])
    shifted_img = cv2.warpAffine(image,M,(image.shape[1],image.shape[0]))
    display("shifted", shifted_img)

In [15]:
translation(img, -100,-150)

Rotating

In [7]:
display("bird",img)
center = (img.shape[1]//2,img.shape[0]//2)

In [20]:
M = cv2.getRotationMatrix2D(center,90,1)
M

array([[ 6.12323400e-17,  1.00000000e+00, -5.68434189e-14],
       [-1.00000000e+00,  6.12323400e-17,  6.40000000e+02]])

In [21]:
rotate_90 = cv2.warpAffine(img,M,(img.shape[1],img.shape[0]))

In [22]:
display("rotate 90 degrees anti-clockwise", rotate_90)

In [25]:
def rotate(image, angle, scale):
    center = (image.shape[1]//2,image.shape[0]//2)
    M = cv2.getRotationMatrix2D(center,angle,scale)
    rotate_img = cv2.warpAffine(image,M,(img.shape[1],img.shape[0]))
    display("rotate", rotate_img)

In [27]:
rotate(img,45,0.5)

Resizing


In [28]:
img.shape

(640, 640, 3)

In [31]:
img_resize = cv2.resize(img,(300,300),interpolation=cv2.INTER_AREA)
display("resized image",img_resize)

In [32]:
cv2.imshow("original",img)
cv2.imshow("resized image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

Flipping

In [11]:
flip_0 = cv2.flip(img,0) # 1, -1, 0
flip_1 = cv2.flip(img,1) # 1, -1, 0
flip_neg_1 = cv2.flip(img,-1) # 1, -1, 0

In [14]:
cv2.imshow("flip vertical+horizontal",flip_0)
cv2.imshow("flip horizontally",flip_1)
cv2.imshow("flip vertically",flip_neg_1)
cv2.waitKey(0)
cv2.destroyAllWindows()

Cropping

In [25]:

crop = img[80:500,100:500]
cv2.imshow("crop",crop)
cv2.waitKey(0)
cv2.destroyAllWindows()