In [2]:
import cv2
import numpy as np

### Grayscale

In [8]:
image = cv2.imread("./camus.jpg", cv2.IMREAD_GRAYSCALE)
print(image.shape)
print(image)

(185, 272)
[[ 96 103 111 ... 201 201 201]
 [ 89  96 104 ... 196 196 196]
 [ 81  89  97 ... 189 189 189]
 ...
 [ 44  44  44 ... 135 133 132]
 [ 45  45  45 ... 140 139 137]
 [ 47  47  48 ... 139 137 135]]


In [9]:
cv2.imshow("albert camus", image)
cv2.waitKey()
cv2.destroyAllWindows()

### Colored image

In [4]:
original = cv2.imread("./cv_course_materials/bird.jpg", cv2.IMREAD_COLOR)


In [5]:
cv2.imshow("original image", original)
cv2.imshow("result_image", result_image)
cv2.waitKey()
cv2.destroyAllWindows()

### Edge Detection

In [9]:
original = cv2.imread("./cv_course_materials/bird.jpg", cv2.IMREAD_COLOR)

# we have to transform the image into grayscale
gray_image = cv2.cvtColor(original,cv2.COLOR_BGR2GRAY)

# lalacian kernel
kernel = np.array([[0,1,0],[1,-4,1],[0,1,0]])

result_image = cv2.Laplacian(gray_image,-1)

kernel = np.ones((5,5))/25
blur_image = cv2.filter2D(original,-1,kernel)

#gaussian blur to reduce noice in an image


In [10]:
cv2.imshow("original image", gray_image)
cv2.imshow("result_image", result_image)
cv2.waitKey()
cv2.destroyAllWindows()

### Sharpen Image

In [17]:
original = cv2.imread("./cv_course_materials/bird.jpg", cv2.IMREAD_COLOR)

# sharpen kernel
# if blurry video or image apply sharpen kernel
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])

sharpen_image = cv2.filter2D(original,-1,kernel)


In [18]:
cv2.imshow("original image", original)
cv2.imshow("sharpen_image", sharpen_image)
cv2.waitKey()
cv2.destroyAllWindows()